# Generated by Django 2.2.19 on 2023-11-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20230922_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='author_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Автор проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='author_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Автор проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='staff',
            name='employee_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя сотрудника'),
        ),
        migrations.AddField(
            model_name='staff',
            name='employee_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Имя сотрудника'),
        ),
        migrations.AddField(
            model_name='staff',
            name='position_en',
            field=models.TextField(null=True, verbose_name='Звание/Должность'),
        ),
        migrations.AddField(
            model_name='staff',
            name='position_ru',
            field=models.TextField(null=True, verbose_name='Звание/Должность'),
        ),
        migrations.AddField(
            model_name='staff',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст о сотруднике'),
        ),
        migrations.AddField(
            model_name='staff',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст о сотруднике'),
        ),
    ]
